if(NOT DEFINED ENV{ASCEND_HOME_PATH})
    message(FATAL_ERROR "Cannot find ASCEND_HOME_PATH, please run set_env.sh.")
else()
    set(ASCEND_HOME_PATH $ENV{ASCEND_HOME_PATH})
endif()

message(${CMAKE_CURRENT_LIST_DIR})
set(ASCEND_CMAKE_PATH ${CMAKE_CURRENT_LIST_DIR}/modules)
list(APPEND CMAKE_MODULE_PATH ${ASCEND_CMAKE_PATH})
if(NOT DEFINED CANN_VERSION)
find_program(BISHENG_COMPILER NAMES bisheng HINTS ${ASCEND_HOME_PATH}/compiler/ccec_compiler/bin)
cmake_path(GET ASCEND_HOME_PATH PARENT_PATH ASCEND_HOME_PATH_DIR)
execute_process(
    COMMAND readlink -f ${BISHENG_COMPILER}
    OUTPUT_VARIABLE BISHENG_COMPILER
)
string(REPLACE "${ASCEND_HOME_PATH_DIR}/" "" BISHENG_COMPILER ${BISHENG_COMPILER})
string(REPLACE "/" ";" BISHENG_COMPILER ${BISHENG_COMPILER})
list(GET BISHENG_COMPILER 0 CANN_VERSION)
message("CANN_VERSION: ${CANN_VERSION}")
endif()

set(CATLASS_FOUND TRUE)
set(CATLASS_ROOT_DIR ${CMAKE_CURRENT_LIST_DIR}/../)

find_path(CATLASS_INCLUDE_DIR NAMES catlass/catlass.hpp
    HINTS ${CATLASS_ROOT_DIR}/include
)
mark_as_advanced(CATLASS_INCLUDE_DIR)

set(CATLASS_INCLUDE_DIRS ${CATLASS_INCLUDE_DIR})
message("catlass-config.cmake: ${CATLASS_ROOT_DIR}")